---
- name: "Configure {{ wtd_nginx_conf_path }}"
  file:
    path: "{{ wtd_nginx_conf_path }}"
    state: directory
    mode: 0755
  become: yes
  notify:
   - Restart nginx

- name: "Configure {{ wtd_nginx_vhost_path }}"
  file:
    path: "{{ wtd_nginx_vhost_path }}"
    state: directory
    mode: 0755
  become: yes
  notify:
    - Reload nginx

- name: "Configure {{ wtd_nginx_ssl_path }}"
  file:
    path: "{{ wtd_nginx_ssl_path }}"
    state: directory
    owner: "{{ wtd_nginx_user }}"
    group: "{{ wtd_nginx_group }}"
    mode: 0700
  become: yes

- name: Configure dhparam
  openssl_dhparam:
    path: "/etc/nginx/ssl/dhparam.pem"
    owner: "{{ wtd_nginx_user }}"
    group: "{{ wtd_nginx_group }}"
    mode: 0600
    state: "present"
  become: yes

- name: Configure nginx main configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ wtd_nginx_conf_path }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
    validate: "/usr/sbin/nginx -t -c %s"
  become: yes
  notify:
   - Reload nginx
