---
- name: Install nginx
  package:
    name: "{{ wtd_nginx_packages }}"
    state: "{{ wtd_nginx_state }}"
  become: yes

- name: Include Configuration Tasks
  include_tasks: configure.yml
  when: wtd_nginx_state != "absent"

- name: Enable and Start nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
  when: wtd_nginx_state != "absent"
